spring:
  profiles:
    active: dev
info:
  launchedOn: default
  apiCallLimit: 5
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, users
  metrics:
    web:
      server:
        auto-time-requests: true
com:
  ivankrn:
    kafka:
      bootstrap-servers: localhost:9092